#!/bin/bash

vimbox_setup() {
	mkdir -p "$HOME/go/pkg"
	xhost +"local:podman@"
}

vimbox() {
	dname=$(basename "$(pwd)")
	podman run \
			-e DISPLAY \
			--net host \
			--rm -it \
			--name vimbox-"$dname" \
			--workdir "/src/" \
			-v ".:/src/" \
			-v "$HOME/.ssh:/root/.ssh" \
			-v "$HOME/go/pkg:/root/go/pkg" \
			--mount=type=volume,target=/root/go/bin \
			--mount=type=volume,target=/root/.cache/go-build \
			--ulimit nofile=10000:10000 \
			workspace-local:latest $@
}
