#!/bin/bash
docker run --rm -it \
	-v ".:/src/" \
	-w "/src/" \
	-v "$HOME/.ssh:/root/.ssh" \
	-v "$HOME/go/pkg:/root/go/pkg" \
	-v "$HOME/.cache/go-build:/root/.cache/go-build" \
	-v /var/run/docker.sock:/var/run/docker.sock \
	--ulimit nofile=5000:5000 \
	gobox vim $1
