#!/bin/bash -ex
dirs=$(cat $1/go.mod | grep 'v' | grep '/' | sed 's|// indirect||' | sed "s,^[[:space:]]*,$HOME/go/pkg/mod/," | sed 's/ /@/' | sed 's/[[:space:]]*$/\//')
rg --glob \*.go --files $dirs | ctags -f $1/globaltags --sort=yes --recurse=yes -L -
